export const ADD_TASK = "ADD_TASK"
export const ADD_CLIENT = "ADD_CLIENT"
export const ADD_COST = "ADD_COST"
export const DELETE_COST = "DELETE_COST"
export const FETCH_COSTS = "FETCH_COSTS"
export const FETCH_CLIENTS = "FETCH_CLIENTS"
export const DELETE_CLIENT = "DELETE_CLIENT"